import { DepartmentGuideBook, GuideModule } from '../department-guide.models';

function field(name: string, required: boolean, note?: string) {
  return { name, required, note };
}

function moduleGuide(partial: GuideModule): GuideModule {
  return partial;
}

export const ENGINEERING_GUIDE: DepartmentGuideBook = {
  department: 'Engineering',
  aliases: ['engineering', 'engg', 'maintenance'],
  title: 'Engineering Department — Operation & Functioning Guide',
  overview:
    'This guidebook explains how Engineering modules in Medicap are operated day-to-day: preventive & breakdown maintenance, calibration, utilities (AHU, water, electricity, compressors), equipment history, and related intimations. Follow module procedures exactly; do not bypass compulsory fields or approval steps.',
  departmentFlow: [
    'Login → Engineering Department dashboard',
    'Select module (Preventive / Calibration / Breakdown / Utilities)',
    'Review due / pending work and PM Intimation if applicable',
    'Complete activity with compulsory fields → Save / Submit',
    'Checking / acceptance by authorized person',
    'Record available in logs / history cards',
  ],
  generalPrecautions: [
    'Do not close or overwrite completed GMP records without authorized correction process.',
    'Always verify equipment ID / tag before recording maintenance or calibration.',
    'PM / Inspection work should proceed only after Intimation is Accepted where the screen enforces it.',
    'Use correct plant context; records are plant-specific.',
    'Logout after shift; do not share login credentials.',
  ],
  modules: [
    moduleGuide({
      id: 'preventive',
      title: 'Preventive Maintenance',
      routeKeys: ['preventive', 'preventivemaint'],
      purpose:
        'Plan, intimate, accept, and execute preventive maintenance for equipment marked Applicable for PM. Ensures due dates and frequencies are tracked.',
      flowSteps: [
        'Open Preventive Maint.',
        'View due / pending equipment schedule',
        'Send / Accept PM Intimation',
        'Execute PM when status allows',
        'Enter observations & save',
        'Complete / close activity',
      ],
      workflow: [
        'Open Engineering → Preventive Maint.',
        'Filter / locate the equipment due for PM.',
        'Use PM Intimation to notify the concerned department; wait until status is Accepted before starting restricted actions.',
        'Open the pending PM record and enter all compulsory fields (equipment, due type, frequency, remarks, done-by).',
        'Attach observations / checklist items as configured.',
        'Save and ensure status updates from Pending to Completed / In-process as designed.',
        'Verify the entry appears in the equipment maintenance history.',
      ],
      precautions: [
        'Do not start PM entry if intimation_status is not Accepted when the button is disabled for that reason.',
        'Do not change frequency / schedule mid-cycle without authorized schedule update.',
        'Confirm next due dates after completion.',
      ],
      compulsoryFields: [
        field('Equipment', true, 'Select correct equipment ID'),
        field('Due type / Frequency', true),
        field('Remark / Observation', true),
        field('Entry by / Done by', true, 'System may auto-fill from login'),
      ],
      optionalFields: [
        field('Additional remarks', false),
        field('Attachments / photos', false, 'If screen supports'),
      ],
      instructions: [
        'Use color-coded action buttons (overdue / due today / upcoming) only for Pending records.',
        'Intimation modal: add Intimation To, send, then Accept from receiving side.',
        'After Accept, PM action buttons become enabled.',
      ],
    }),
    moduleGuide({
      id: 'inspection',
      title: 'Inspection (Preventive schedule)',
      routeKeys: ['inspection'],
      purpose: 'Track inspection due dates linked to equipment inspection frequencies and raise Inspection Intimation.',
      flowSteps: [
        'Open Inspection list',
        'Review remaining days',
        'Send / Accept Inspection Intimation',
        'Perform inspection entry',
        'Save & close',
      ],
      workflow: [
        'Open Engineering preventive / inspection screens as provided.',
        'Identify overdue or due inspection rows.',
        'Raise Inspection Intimation to the department owning the equipment area.',
        'After acceptance, record inspection results with compulsory fields.',
        'Save and confirm status change.',
      ],
      precautions: [
        'Do not skip intimation when the process requires acceptance.',
        'Record actual inspection date accurately.',
      ],
      compulsoryFields: [
        field('Equipment', true),
        field('Inspection particular / frequency', true),
        field('Remark', true),
      ],
      optionalFields: [field('Extra observations', false)],
      instructions: [
        'Follow the same intimation → accept → execute pattern as PM.',
        'Use View buttons only on allowed status combinations.',
      ],
    }),
    moduleGuide({
      id: 'calibration',
      title: 'Calibration',
      routeKeys: ['calibration'],
      purpose: 'Maintain calibration schedules and records for engineering equipment / instruments.',
      flowSteps: [
        'Open Calibration',
        'Select due instrument / equipment',
        'Enter calibration data',
        'Save / submit for check',
        'File certificate if applicable',
      ],
      workflow: [
        'Open Engineering → Calibration.',
        'Select the instrument due for calibration.',
        'Enter calibration results, standards used, and next due date.',
        'Fill all compulsory fields; mark out-of-tolerance as per procedure.',
        'Save and route for checking / approval if the screen requires it.',
      ],
      precautions: [
        'Do not use an instrument past its calibration due date for GMP work.',
        'Record standard / reference IDs used during calibration.',
      ],
      compulsoryFields: [
        field('Instrument / Equipment ID', true),
        field('Calibration date', true),
        field('Result / status', true),
        field('Next due date', true),
      ],
      optionalFields: [field('Certificate number', false), field('Remarks', false)],
      instructions: [
        'Verify master data of the instrument before posting results.',
        'If OOC (out of calibration) workflow exists, follow that module separately.',
      ],
    }),
    moduleGuide({
      id: 'breakdown',
      title: 'Breakdown Maintenance',
      routeKeys: ['maintenance', 'breakdown'],
      purpose: 'Log unexpected equipment failures, corrective actions, and restoration.',
      flowSteps: [
        'Raise / open breakdown',
        'Record fault & equipment',
        'Perform corrective action',
        'Close with verification',
      ],
      workflow: [
        'Open Engineering → Breakdown Maint. (or shared Breakdown link).',
        'Create or open the breakdown ticket for the failed equipment.',
        'Describe fault, downtime, and action taken.',
        'Complete compulsory fields and close after equipment is released.',
      ],
      precautions: [
        'Do not release equipment for production until corrective action is recorded.',
        'Link to related QMS deviation if quality impact is suspected.',
      ],
      compulsoryFields: [
        field('Equipment', true),
        field('Fault description', true),
        field('Action taken', true),
        field('Done by / date', true),
      ],
      optionalFields: [field('Spare parts used', false), field('Root cause', false)],
      instructions: ['Use clear, factual language in fault and action fields.', 'Update status promptly after restoration.'],
    }),
    moduleGuide({
      id: 'utilities',
      title: 'Utilities (AHU / Water / Electricity / Air Compressor / Nitrogen / Chilling)',
      routeKeys: ['ahu', 'water', 'electricity', 'aircompressor', 'nitrogen', 'en020', 'soft-water', 'purifiedwater', 'thermic-boiler'],
      purpose: 'Operate and record utility systems supporting manufacturing and labs.',
      flowSteps: [
        'Select utility module',
        'Open daily / shift log or activity',
        'Enter readings & checks',
        'Save / check',
      ],
      workflow: [
        'From Engineering dashboard open the relevant utility tile (AHU, Water System Docs., Electricity, Air Compressor, Nitrogen, Chilling & Brine, etc.).',
        'Select the logbook / activity for the current date or shift.',
        'Enter all compulsory readings and checklist responses.',
        'Save; complete checking where required.',
      ],
      precautions: [
        'Out-of-limit readings must be escalated as per site SOP.',
        'Do not back-date readings unless authorized.',
      ],
      compulsoryFields: [
        field('Date / shift', true),
        field('System / equipment identity', true),
        field('Critical readings / checks', true),
        field('Entry by', true),
      ],
      optionalFields: [field('Remarks', false)],
      instructions: [
        'Nutraceutical plants may hide some utility tiles — use only modules shown for your software type.',
        'Keep entries consistent with paper logbooks if dual recording is required.',
      ],
    }),
    moduleGuide({
      id: 'equip-history',
      title: 'Equipment History Card',
      routeKeys: ['external', 'equip-qualification'],
      purpose: 'Maintain historical maintenance / event records for equipment.',
      flowSteps: ['Open Equip. History Card', 'Select equipment', 'Review / add history entry', 'Save'],
      workflow: [
        'Open Engineering → Equip. History Card.',
        'Search and select equipment.',
        'Review prior events; add new history entry if authorized.',
        'Save with compulsory identification fields.',
      ],
      precautions: ['Do not alter historical signed records without change control.'],
      compulsoryFields: [field('Equipment ID', true), field('Event / activity', true), field('Date', true)],
      optionalFields: [field('Reference document', false)],
      instructions: ['Cross-check equipment tag on floor before selecting ID in software.'],
    }),
    moduleGuide({
      id: 'pm-intimation',
      title: 'PM Intimation (cross-department)',
      purpose: 'Receive and act on Preventive Maintenance intimations from Engineering via /preventiveimain.',
      flowSteps: [
        'Open PM Intimation from sidebar',
        'Review pending intimations',
        'Accept / view details',
        'Coordinate equipment availability',
      ],
      workflow: [
        'Click PM Intimation on the department sidebar.',
        'Review equipment and schedule details.',
        'Accept when area can release equipment for PM / inspection.',
        'Coordinate with Engineering for execution timing.',
      ],
      precautions: ['Accepting means the area acknowledges the planned activity.', 'Do not ignore overdue intimations.'],
      compulsoryFields: [field('Acceptance action', true)],
      optionalFields: [field('Comment', false)],
      instructions: ['Available from every department sidebar for coordination.'],
    }),
  ],
};

export const QC_GUIDE: DepartmentGuideBook = {
  department: 'Quality Control',
  aliases: ['qc', 'quality control', 'qualitycontrol', 'q c'],
  title: 'Quality Control Department — Operation & Functioning Guide',
  overview:
    'This guidebook covers QC laboratory operations in Medicap: specifications, sampling, testing (RDS), water analysis, standards & reagents, equipment, calibration, control samples, retest, OOS, change control / deviation, and material / FG approvals. Always complete compulsory analytical fields and follow status workflows.',
  departmentFlow: [
    'Login → QC Department dashboard',
    'Select Lab / Standards / Equipment / QMS / Approval module',
    'Receive sample or open pending test',
    'Perform analysis → enter results (compulsory fields)',
    'Review / check / approve as per role',
    'Release status updates to Store / Production / QA as designed',
  ],
  generalPrecautions: [
    'Do not release material / product without completing required tests and signatures.',
    'OOS results must follow OOS module — do not overwrite failing data casually.',
    'Use calibrated instruments only; verify calibration status before use.',
    'Maintain audit trail integrity; corrections must be justified.',
    'Plant and specification version must match the sample under test.',
  ],
  modules: [
    moduleGuide({
      id: 'sampling',
      title: 'Sampling',
      routeKeys: ['sampling', 'presampling', 'sampling-room', 'booth-monitoring', 'rm-pm-grn-receiving'],
      purpose: 'Plan and record sample collection for RM/PM and related QC sampling workflows.',
      flowSteps: [
        'Open Sampling',
        'Select GRN / request / intimation',
        'Withdraw sample',
        'Send intimation / hand over to lab',
        'Update status',
      ],
      workflow: [
        'Open QC → Sampling.',
        'Locate the pending sampling request / GRN line.',
        'Enter sampling details and compulsory fields (container, qty, location).',
        'Complete withdraw / send intimation actions as shown on screen.',
        'Ensure sample ID / Medicap Lot No continuity into testing.',
      ],
      precautions: [
        'Sample only from identified containers.',
        'Follow gowning and booth monitoring requirements where applicable.',
      ],
      compulsoryFields: [
        field('Material / batch identity', true),
        field('Sample quantity', true),
        field('Sampled by / date', true),
      ],
      optionalFields: [field('Remarks', false), field('Additional container IDs', false)],
      instructions: ['Use Intimation Receiving screens when sample is raised from other departments.', 'Do not mix samples from different batches.'],
    }),
    moduleGuide({
      id: 'testing',
      title: 'Testing (RDS)',
      routeKeys: ['testing-rds', 'testinggmp-rds', 'raw', 'finish', 'inprocess', 'stability', 'oosreview'],
      purpose: 'Perform and record raw / packing / in-process / finished / stability testing as configured.',
      flowSteps: [
        'Open Testing',
        'Select sample / Medicap Lot No',
        'Enter test results vs specification',
        'Complete checklist / worksheets',
        'Submit for review / approval',
      ],
      workflow: [
        'Open QC → Testing.',
        'Select the pending sample.',
        'Enter each test parameter result against the approved specification.',
        'Mark compulsory tests; leave optional only if procedure allows skip with justification.',
        'Save and move to chemist / review / approval stage.',
      ],
      precautions: [
        'Do not finalize if any compulsory test is blank.',
        'Out-of-spec → initiate OOS as per site procedure.',
      ],
      compulsoryFields: [
        field('Medicap Lot No / Sample ID', true),
        field('Test results', true),
        field('Specification reference', true),
        field('Analyzed by', true),
      ],
      optionalFields: [field('Additional observations', false), field('Chromatogram attachment', false)],
      instructions: ['Follow on-screen status (Under Test → Checked → Approved).', 'Verify instrument ID used for instrumental tests.'],
    }),
    moduleGuide({
      id: 'specifications',
      title: 'Specifications',
      purpose: 'Refer / use approved raw & packing material specifications linked from Master / QC.',
      flowSteps: ['Open Specifications', 'Select material', 'Review version', 'Use during testing'],
      workflow: [
        'Open Specifications from QC dashboard (or Master link provided).',
        'Confirm correct material code and effective version.',
        'Use limits while entering test results.',
      ],
      precautions: ['Never test against superseded specification versions.', 'Changes require change control.'],
      compulsoryFields: [field('Material code', true), field('Version / effective status', true)],
      optionalFields: [field('Search filters', false)],
      instructions: ['If revision is needed, raise through Master / Change Control — do not edit live approved specs casually.'],
    }),
    moduleGuide({
      id: 'standards-reagents',
      title: 'Standards & Reagents / Chemical / Volumetric',
      purpose: 'Manage working / reference standards, reagents, and volumetric solutions used in analysis.',
      flowSteps: ['Open Standards / Reagents / Volumetric', 'Create or select lot', 'Record prep / usage', 'Monitor expiry'],
      workflow: [
        'Open the relevant Standards, Reagents, Chemical, or Volumetric module.',
        'Create preparation / receipt entry with compulsory identity and expiry.',
        'Record usage against tests where required.',
        'Quarantine / discard expired materials.',
      ],
      precautions: ['Do not use expired standards or reagents.', 'Label physical containers to match system IDs.'],
      compulsoryFields: [
        field('Name / code', true),
        field('Lot / batch', true),
        field('Expiry / retest date', true),
        field('Prepared / received by', true),
      ],
      optionalFields: [field('Potency / factor', false), field('Storage condition note', false)],
      instructions: ['Update inventory after each preparation.', 'Link volumetric factor to titration worksheets when prompted.'],
    }),
    moduleGuide({
      id: 'equipment-calib',
      title: 'Equipment & Calibration',
      purpose: 'Track lab equipment status and calibration due dates for QC instruments.',
      flowSteps: ['Open Equipment / Calibration', 'Check due list', 'Perform / record calibration', 'Update status'],
      workflow: [
        'Open QC Equipment or Calibration module.',
        'Review due / overdue instruments.',
        'Record calibration activity with compulsory fields.',
        'Ensure instrument status is Active / Calibrated before use in testing.',
      ],
      precautions: ['Do not assign tests to out-of-calibration instruments.'],
      compulsoryFields: [
        field('Instrument ID', true),
        field('Calibration date', true),
        field('Next due', true),
        field('Result', true),
      ],
      optionalFields: [field('Certificate no.', false)],
      instructions: ['Cross-check with Engineering calibration where instruments are shared.'],
    }),
    moduleGuide({
      id: 'control-retest',
      title: 'Control Sample & Retest',
      purpose: 'Manage control sample storage / withdrawal and material retest programs.',
      flowSteps: ['Open Control Sample / Retest', 'Select batch', 'Withdraw or schedule retest', 'Record results'],
      workflow: [
        'Open Control Sample or Retest from QC dashboard.',
        'Identify batch / Medicap Lot No',
        'For withdrawal, enter qty and reason; for retest, follow sampling → testing chain.',
        'Complete compulsory fields and save.',
      ],
      precautions: ['Control sample withdrawals must be justified and recorded.', 'Retest failures follow OOS / disposition process.'],
      compulsoryFields: [field('Batch / Medicap Lot No', true), field('Quantity / action', true), field('Done by', true)],
      optionalFields: [field('Remarks', false)],
      instructions: ['Keep physical inventory aligned with system balances.'],
    }),
    moduleGuide({
      id: 'oos-qms',
      title: 'OOS / Change Control / Deviation',
      purpose: 'Handle out-of-specification investigations and QC-side QMS activities.',
      flowSteps: ['Detect OOS / event', 'Open OOS or QMS module', 'Investigate & document', 'Close with QA as required'],
      workflow: [
        'When a result is OOS, open OOS module (do not silently alter result).',
        'Fill investigation phases / checklists as configured.',
        'For change control or deviation raised from QC, use respective modules and complete compulsory impact fields.',
        'Route for review / approval.',
      ],
      precautions: [
        'Never delete failing raw data.',
        'Timelines for Phase investigations must be respected.',
      ],
      compulsoryFields: [
        field('Event / OOS reference', true),
        field('Description', true),
        field('Immediate action', true),
      ],
      optionalFields: [field('Attachments', false)],
      instructions: ['Coordinate with QA for cross-functional closures.', 'Use PM Intimation / Breakdown links from sidebar when equipment issues cause delays.'],
    }),
    moduleGuide({
      id: 'approvals',
      title: 'Material & FG Product Approval',
      purpose: 'Approve materials / finished goods based on completed testing and documentation.',
      flowSteps: ['Open Approval screen', 'Review test status', 'Confirm compulsory checks', 'Approve / reject'],
      workflow: [
        'Open Material Approval or FG Product Approval.',
        'Verify all tests are complete and within specification.',
        'Complete compulsory approval fields and e-sign / password if prompted.',
        'Confirm status reflects in Store / Dispatch.',
      ],
      precautions: ['Do not approve with pending tests.', 'Reject with clear reason when required.'],
      compulsoryFields: [field('Decision (Approve/Reject)', true), field('Approved by', true)],
      optionalFields: [field('Comments', false)],
      instructions: ['Validate COA / worksheet completeness before final approval.'],
    }),
  ],
};
