export interface EmpModel {
    id: string
    plant_id: string
    user_no: string
    employee_type: string
    emp_id: string
    firstname: string
    middlename: string
    lastname: string
    contact_no: string
    emp_email: string
    department: string
    operator_category: string
    qualification: string
    birthdate: string
    gender: string
    pan: string
    adhar: string
    country: string
    address_permanent: string
    permanant_state: string
    permanant_district: string
    permanant_taluka: string
    address_temporary: string
    temporary_state: string
    temporary_district: string
    temporary_taluka: string
    emergency_no: string
    interview_date: any
    joining_date: string
    section: string
    resume: string
    photo: string
    isinduction: string
    password: string
    isAppointment: string
    designation: string
    isuser: string
    ischecker: string
    isapprover: string
    status: string
    resign_by: string
    resign_date: any
    ISNEW: string
    induction_training: string
    emp_name: string
    emp_contact: string
    emp_password: string
    emp_id1: string
    details: string
    status1: string
    approve_by: string
    approve_date: string
    email: string
    joining_status: string
    trainee_period: string
    probation_period: string
    experience: string
    branch_name: string
    nationality: string
    category: string
    account_no: string
    marital_status: string
    blood_group: string
    reg_no: string
    anni_date: string
    registration_date: string
    renewal_date: string
    induction: string
    result: string
    permanent_flat: string
    permanent_country: string
    permanent_state: string
    permanent_city: string
    permanent_pincode: string
    permanent_telephone: string
    permanent_mobile_no: string
    permanent_contact: string
    tempflat_no: string
    temp_country: string
    temp_state: string
    temp_city: string
    temp_pincode: string
    temp_telephone: string
    temp_mobile: string
    temp_contact: string
    familyList: string
    qualification1: string
    specialization: string
    institute_name: string
    institute_add: string
    board: string
    obtained_mark: string
    year_from: string
    year_to: string
    qualification2: string
    subject: string
    clg_name: string
    last_salary: string
    location: string
    from_year: string
    to_year: string
    Languages: string
    qualiList: string
    company_name: string
    position: string
    duties: string
    address: string
    year_from1: string
    year_to1: string
    gross_sal: string
    reason: string
    training: string
    activity: string
    general: string
    name: string
    designation1: string
    department1: string
    relation: string
    salary1: string
    pf_no: string
    esi_no: string
    ref_name: string
    emp_present: string
    ref_add: string
    tel_no: string
    document: string
    description: string
    doc: string
    basic: string
    department2: string
    time: string
    lunch_duration: string
    per_annum: string
    leave1: string
    bonus: string
    resignation_date: string
    emp_no: string
    institute_add1: string
    min_salary: string
    ai_data_object: string
    ai_data_object_updated_on: string
    ai_data_object_updated_by: string
    esic_no: string
    academics: string
    document_list: string
    salary_details: string
    acc_name: string
    bank_name: string
    ifsc_neft: string
    acc_type: string
    employeement_list: string
    salary_list: string
  }
  