<?php
/** Default QC lab chemical seed list for Chemical Master. */
function medicap_standard_chemicals_seed() {
    return array(
    array('chemical_name' => "Ammonium Chloride", 'molecular_wt' => "53.491", 'cas_name' => "12125-02-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ammonium molybdate", 'molecular_wt' => "196.01", 'cas_name' => "13106-76-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ammonium Thiocynate", 'molecular_wt' => "76.12", 'cas_name' => "1762-95-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ammonium Acetate", 'molecular_wt' => "77.08", 'cas_name' => "631-61-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Barium Chloride", 'molecular_wt' => "208.23", 'cas_name' => "10361-37-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Barium Sulphate", 'molecular_wt' => "233.39", 'cas_name' => "7727-43-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Boric Acid", 'molecular_wt' => "61.83", 'cas_name' => "10043-35-3", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Benzoyal Chloride", 'molecular_wt' => "140.57", 'cas_name' => "98-88-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Calcium Carbonate", 'molecular_wt' => "100.09", 'cas_name' => "471-34-1", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Calcium Chloride", 'molecular_wt' => "110.98", 'cas_name' => "10043-52-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Citric Acid", 'molecular_wt' => "192.12", 'cas_name' => "77-92-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Cupric Acid", 'molecular_wt' => "211.62", 'cas_name' => "946843-80-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Cupric Sulphate", 'molecular_wt' => "159.61", 'cas_name' => "7758-98-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Dextrose Anhydrous", 'molecular_wt' => "180.156", 'cas_name' => "50-99-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Eriochrome Black T", 'molecular_wt' => "461.38", 'cas_name' => "1787-61-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ferric Chloride", 'molecular_wt' => "162.2", 'cas_name' => "7705-08-0", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ferrous Sulphate", 'molecular_wt' => "278.01", 'cas_name' => "7782-63-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Hydroquinone", 'molecular_wt' => "110.11", 'cas_name' => "123-31-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Lead Nitrate", 'molecular_wt' => "331.21", 'cas_name' => "10099-74-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Mercuric Chloride", 'molecular_wt' => "271.52", 'cas_name' => "7487-94-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium Bromide", 'molecular_wt' => "119", 'cas_name' => "7758-02-3", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium Chloride", 'molecular_wt' => "74.55", 'cas_name' => "7447-40-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium Di Chromate", 'molecular_wt' => "294.18", 'cas_name' => "7778-50-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium Chromate", 'molecular_wt' => "194.19", 'cas_name' => "7789-00-6", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium Iodide", 'molecular_wt' => "166", 'cas_name' => "7681-11-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium Per Magnate", 'molecular_wt' => "158.03", 'cas_name' => "7722-64-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium Nitrate", 'molecular_wt' => "101.1", 'cas_name' => "7757-79-1", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Phosphoric Acid", 'molecular_wt' => "98", 'cas_name' => "7664-38-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Silica Gel", 'molecular_wt' => "60.08", 'cas_name' => "7631-86-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Acetate", 'molecular_wt' => "82.03", 'cas_name' => "127-09-3", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Bicarbonate", 'molecular_wt' => "84.01", 'cas_name' => "144-55-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Chloride", 'molecular_wt' => "58.44", 'cas_name' => "7647-14-5", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Citrate Anhydrous", 'molecular_wt' => "258.07", 'cas_name' => "68-04-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Nitrate", 'molecular_wt' => "84.99", 'cas_name' => "7631-99-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Thiosulfate", 'molecular_wt' => "158.11", 'cas_name' => "7772-98-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Sulphate", 'molecular_wt' => "142.04", 'cas_name' => "7757-82-6", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Stannous Chloride", 'molecular_wt' => "189.61", 'cas_name' => "7772-99-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sucrose", 'molecular_wt' => "342.3", 'cas_name' => "57-50-1", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Starch", 'molecular_wt' => "342.3", 'cas_name' => "9005-84-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Acetate Trihydrate", 'molecular_wt' => "136.08", 'cas_name' => "6131-90-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Tetra Borate", 'molecular_wt' => "201.22", 'cas_name' => "1330-43-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Zinc Sulphate", 'molecular_wt' => "179.47", 'cas_name' => "7446-19-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Zinc powder", 'molecular_wt' => "65.39", 'cas_name' => "7440-66-6", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ammonium Hydroxide", 'molecular_wt' => "35.05", 'cas_name' => "1336-21-6", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "1,4 Benzequinone", 'molecular_wt' => "108.09", 'cas_name' => "106-51-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Chloride Hexa Hydrate", 'molecular_wt' => "237.93", 'cas_name' => "7791-13-1", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Calcium Acetate", 'molecular_wt' => "158.17", 'cas_name' => "62-54-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Di Sodium Edetate", 'molecular_wt' => "372.24", 'cas_name' => "6381-92-6", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ferric Ammonium Sulphate", 'molecular_wt' => "482.19", 'cas_name' => "7783-83-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Iodine", 'molecular_wt' => "126.9", 'cas_name' => "7553-56-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Lanthanium Chloride", 'molecular_wt' => "245.26", 'cas_name' => "10099-58-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Linthium Nitrate", 'molecular_wt' => "68.95", 'cas_name' => "7790-69-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Magnesium Sulphate", 'molecular_wt' => "120.37", 'cas_name' => "7487-88-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Magnesium Chloride", 'molecular_wt' => "95.21", 'cas_name' => "7786-30-3", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium Mercuric Iodide", 'molecular_wt' => "786.4", 'cas_name' => "7783-33-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium Phosphate", 'molecular_wt' => "136.086", 'cas_name' => "7778-77-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Pantate Sulphonate", 'molecular_wt' => "176.21", 'cas_name' => "22767-49-3", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Acetic Anhydride", 'molecular_wt' => "102.09", 'cas_name' => "108-24-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Acetone", 'molecular_wt' => "58.08", 'cas_name' => "67-64-1", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Acetonitrile HPLC", 'molecular_wt' => "41.05", 'cas_name' => "75-05-8", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ammonia Solution", 'molecular_wt' => "35.04", 'cas_name' => "1336-21-6", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Benzene Crystalizable", 'molecular_wt' => "78.11", 'cas_name' => "71-43-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "1 - Butanol", 'molecular_wt' => "74.12", 'cas_name' => "71-43-2", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Chloroform", 'molecular_wt' => "119.37", 'cas_name' => "67-66-3", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Di - Chloromethane", 'molecular_wt' => "84.93", 'cas_name' => "75-09-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Di - Ethyl Amine", 'molecular_wt' => "73.14", 'cas_name' => "109-89-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Di - Oxan", 'molecular_wt' => "88.11", 'cas_name' => "123-91-1", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Formaldehyde", 'molecular_wt' => "30.03", 'cas_name' => "50-00-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Formic Acid", 'molecular_wt' => "46.03", 'cas_name' => "64-18-6", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Glycerene", 'molecular_wt' => "92.09", 'cas_name' => "56-81-5", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Hexamine", 'molecular_wt' => "140.19", 'cas_name' => "100-97-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Hydrochloric Acid", 'molecular_wt' => "36.46", 'cas_name' => "7647-01-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Methanol", 'molecular_wt' => "32.042", 'cas_name' => "67-56-1", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Methanol HPLC", 'molecular_wt' => "32.04", 'cas_name' => "67-56-1", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Nitric Acid", 'molecular_wt' => "63.02", 'cas_name' => "7697-37-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Paraffin Liquid", 'molecular_wt' => "", 'cas_name' => "0.00", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Perchloric Acid", 'molecular_wt' => "100.46", 'cas_name' => "7601-90-3", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Pyridine", 'molecular_wt' => "79.1", 'cas_name' => "110-86-1", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sulphuric Acid", 'molecular_wt' => "", 'cas_name' => "98.08", 'grade' => "Commercial", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Triethylamine", 'molecular_wt' => "101.19", 'cas_name' => "121-44-8", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Chloramine Solution", 'molecular_wt' => "51.47", 'cas_name' => "10599-90-3", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ethanol", 'molecular_wt' => "46.07", 'cas_name' => "64-17-5", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Toluene", 'molecular_wt' => "92.14", 'cas_name' => "108-88-3", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Di Butyl Phthalate", 'molecular_wt' => "278.34", 'cas_name' => "84-74-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Litmus Solution", 'molecular_wt' => "3300", 'cas_name' => "1393-92-6", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Vanillin", 'molecular_wt' => "152.15", 'cas_name' => "121-33-5", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Bismuth Sulphate Agar", 'molecular_wt' => "34.01", 'cas_name' => "7787-68-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Phenoptheline Solution", 'molecular_wt' => "318.32", 'cas_name' => "77-09-8", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium - Di - Hydrogen - Ortho Phosphate", 'molecular_wt' => "136.09", 'cas_name' => "7778-77-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium Ferri Cynide", 'molecular_wt' => "329.24", 'cas_name' => "13746-66-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium Hydrogen Phthalate", 'molecular_wt' => "204.22", 'cas_name' => "877-24-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium Hydroxide Pellates", 'molecular_wt' => "56.11", 'cas_name' => "1310-58-3", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Phosphorus Pentoxide", 'molecular_wt' => "141.94", 'cas_name' => "1314-56-3", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Hydroxide Pellates", 'molecular_wt' => "40", 'cas_name' => "1310-73-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Meta Bi Sulphate", 'molecular_wt' => "190.11", 'cas_name' => "7681-57-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Thiosulphate", 'molecular_wt' => "158.11", 'cas_name' => "7772-98-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Potassium Tartrate", 'molecular_wt' => "210.16", 'cas_name' => "6381-59-5", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Catechol", 'molecular_wt' => "110.11", 'cas_name' => "120-80-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Potassium Gluconate", 'molecular_wt' => "234.25", 'cas_name' => "299-27-4", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Phenyl Iso Cyanide", 'molecular_wt' => "119.12", 'cas_name' => "103-71-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Bromothymol Blue Ind", 'molecular_wt' => "624.38", 'cas_name' => "76-59-5", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ferroin Indicator Solution", 'molecular_wt' => "692.52", 'cas_name' => "14634-91-4", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Methanol Dried for KF", 'molecular_wt' => "32.04", 'cas_name' => "67-56-1", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Methyl Orange Indicator", 'molecular_wt' => "327.34", 'cas_name' => "547-58-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Methyl Red Indicator", 'molecular_wt' => "269.3", 'cas_name' => "493-52-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Methylene Blue Indicator", 'molecular_wt' => "319.85", 'cas_name' => "61-73-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ninhydrin", 'molecular_wt' => "178.14", 'cas_name' => "485-47-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ortho - Phosphoric Acid", 'molecular_wt' => "97.994", 'cas_name' => "7664-38-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Phenol Red Indicator", 'molecular_wt' => "354.38", 'cas_name' => "143-74-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Nile Blue Indicator", 'molecular_wt' => "407.89", 'cas_name' => "3625-57-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Crystal Violet Solution", 'molecular_wt' => "407.98", 'cas_name' => "548-62-9", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Bromo Cresol Purple Solution", 'molecular_wt' => "562.2", 'cas_name' => "62625-30-3", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Acetic Acid", 'molecular_wt' => "60.05", 'cas_name' => "64-19-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Carbon Disulfide", 'molecular_wt' => "76.139", 'cas_name' => "75-15-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Carbon Tetrachloride", 'molecular_wt' => "153.82", 'cas_name' => "56-23-5", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Carbonyldiimidazole", 'molecular_wt' => "162.15", 'cas_name' => "530-62-1", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ceric Ammonium Nitrate", 'molecular_wt' => "548.22", 'cas_name' => "16774-21-3", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Chromic Acid", 'molecular_wt' => "118.01", 'cas_name' => "7789-00-6", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Chromium Trioxide", 'molecular_wt' => "99.994", 'cas_name' => "1333-82-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Collins Reagent", 'molecular_wt' => "258.194", 'cas_name' => "26412-88-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Diborane", 'molecular_wt' => "27.66", 'cas_name' => "19287-45-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Dicyclohexylcarbodiimide", 'molecular_wt' => "206.33", 'cas_name' => "538-75-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Diethyl Azodicarboxylate", 'molecular_wt' => "174.15", 'cas_name' => "1972-28-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Dihydropyran", 'molecular_wt' => "84.12", 'cas_name' => "110-87-2", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Diisobutylaluminium Hydride", 'molecular_wt' => "142.22", 'cas_name' => "1191-15-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Di-isopropyl Azodicarboxylate", 'molecular_wt' => "202.21", 'cas_name' => "2446-83-5", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Dioxane", 'molecular_wt' => "88.11", 'cas_name' => "123-91-1", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Hydrazine", 'molecular_wt' => "32.0452", 'cas_name' => "302-01-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Hydrazoic Acid", 'molecular_wt' => "43.03", 'cas_name' => "7782-79-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Hydrofluoric Acid", 'molecular_wt' => "20.01", 'cas_name' => "7664-39-3", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Hydrogen Peroxide", 'molecular_wt' => "34.01", 'cas_name' => "7722-84-1", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Imidazole", 'molecular_wt' => "68.08", 'cas_name' => "288-32-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Osmium Tetroxide", 'molecular_wt' => "254.23", 'cas_name' => "20816-12-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Oxalyl Chloride", 'molecular_wt' => "254.23", 'cas_name' => "79-37-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Manganese Dioxide", 'molecular_wt' => "86.937", 'cas_name' => "1313-13-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Meta - Chloroperoxybenzoic Acid", 'molecular_wt' => "172.57", 'cas_name' => "937-14-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Methyl Tert - Butyl Ether", 'molecular_wt' => "88.15", 'cas_name' => "1634-04-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Phosphorus Pentachloride", 'molecular_wt' => "208.24", 'cas_name' => "10026-13-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Phosphorus Tribromide", 'molecular_wt' => "270.69", 'cas_name' => "7789-60-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Phosphorus Trichloride", 'molecular_wt' => "137.33", 'cas_name' => "7719-12-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Phosphoryl Chloride", 'molecular_wt' => "153.33", 'cas_name' => "10025-87-3", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Pyridinium Chlorochromate", 'molecular_wt' => "215.56", 'cas_name' => "26299-14-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Pyridinium Dichromate", 'molecular_wt' => "376.2", 'cas_name' => "20039-37-6", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Raney Nickel", 'molecular_wt' => "85.67", 'cas_name' => "7440-02-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Silver Oxide", 'molecular_wt' => "231.74", 'cas_name' => "20667-12-3", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Amide", 'molecular_wt' => "65.01", 'cas_name' => "26628-22-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Azide", 'molecular_wt' => "65.01", 'cas_name' => "26628-22-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Borohydride", 'molecular_wt' => "37.83", 'cas_name' => "16940-66-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Hydride", 'molecular_wt' => "24", 'cas_name' => "7646-69-7", 'grade' => "Commercial", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sodium Hypochlorite Solution", 'molecular_wt' => "74.44", 'cas_name' => "7681-52-9", 'grade' => "Commercial", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Tert - Butyl Hydroperoxide Solution", 'molecular_wt' => "90.12", 'cas_name' => "75-91-2", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Tetramethylammonium Hydroxide", 'molecular_wt' => "91.15", 'cas_name' => "75-59-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Tetramethylsilane", 'molecular_wt' => "88.22", 'cas_name' => "75-76-3", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Thionyl Chloride", 'molecular_wt' => "118.97", 'cas_name' => "7719-09-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Thiophenol", 'molecular_wt' => "110.18", 'cas_name' => "108-98-5", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Titanium Tetrachloride", 'molecular_wt' => "189.7", 'cas_name' => "7550-45-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Dirithromycin", 'molecular_wt' => "835.07", 'cas_name' => "62013-04-1", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Norfloxacin", 'molecular_wt' => "319.33", 'cas_name' => "70458-96-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Spiramycin from Streptomyces sp", 'molecular_wt' => "843.1", 'cas_name' => "8025-81-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sulfanilamide", 'molecular_wt' => "172.2", 'cas_name' => "63-74-1", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Tiamulin", 'molecular_wt' => "493.74", 'cas_name' => "55297-95-5", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Trimethoprim", 'molecular_wt' => "290.32", 'cas_name' => "738-70-5", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Metronidazole", 'molecular_wt' => "171.15", 'cas_name' => "443-48-1", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Enrofloxacin", 'molecular_wt' => "359.39", 'cas_name' => "93106-60-6", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sulfadiazine", 'molecular_wt' => "250.28", 'cas_name' => "68-35-9", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sulfamethazine", 'molecular_wt' => "278.33", 'cas_name' => "57-68-1", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Cefalexin", 'molecular_wt' => "347.39", 'cas_name' => "15686-71-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Novobiocin Sodium Salt", 'molecular_wt' => "634.61", 'cas_name' => "1476-53-5", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Oxytetracycline Hydrochloride", 'molecular_wt' => "496.89", 'cas_name' => "2058-46-0", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sulfasalazine", 'molecular_wt' => "398.39", 'cas_name' => "599-79-1", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Chlortetracycline Hydrochloride", 'molecular_wt' => "575.34", 'cas_name' => "64-72-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sulfadimethoxine", 'molecular_wt' => "310.33", 'cas_name' => "122-11-2", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Polymyxin B Solution", 'molecular_wt' => "1189.36", 'cas_name' => "1405-20-5", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Streptomycin Solution", 'molecular_wt' => "728.69", 'cas_name' => "3810-74-0", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Spectinomycin Dihydrochloride Pentahydrate", 'molecular_wt' => "495.35", 'cas_name' => "22189-32-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Trypsin From Bovine Pancreas", 'molecular_wt' => "23.8", 'cas_name' => "9002-07-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ciprofloxacin", 'molecular_wt' => "331.34", 'cas_name' => "85721-33-1", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Doxycycline Hyclate", 'molecular_wt' => "512.94", 'cas_name' => "24390-14-5", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Peroxidase from Horseradish", 'molecular_wt' => "44", 'cas_name' => "9003-99-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Cellulose Acetate", 'molecular_wt' => "264.23", 'cas_name' => "9004-35-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Benzoin", 'molecular_wt' => "212.24", 'cas_name' => "119-53-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Propyl 4-Hydroxybenzoate Sodium", 'molecular_wt' => "202.18", 'cas_name' => "35285-69-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Methyl 4- Hydroxybenzoate Sodium", 'molecular_wt' => "174.13", 'cas_name' => "5026-62-0", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Dextrin From Maize Starch", 'molecular_wt' => "342.29", 'cas_name' => "9050-36-6", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Antipyrine", 'molecular_wt' => "188.23", 'cas_name' => "60-80-0", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Quinine Hydrochloride Dihydrate", 'molecular_wt' => "396.91", 'cas_name' => "6119-47-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Sulfamic Acid", 'molecular_wt' => "97.09", 'cas_name' => "5329-14-6", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Dexamethasone", 'molecular_wt' => "392.46", 'cas_name' => "50-02-2", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ethylenediaminetetracetic acid disodium", 'molecular_wt' => "372.24", 'cas_name' => "6381-92-6", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Acetic Acid Solution", 'molecular_wt' => "65.05", 'cas_name' => "64-19-7", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Caffeic Acid", 'molecular_wt' => "180.16", 'cas_name' => "331-39-5", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Chlorogenic Acid", 'molecular_wt' => "354.31", 'cas_name' => "327-97-9", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ferulic Acid", 'molecular_wt' => "194.18", 'cas_name' => "1135-24-6", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Gallic Acid", 'molecular_wt' => "170.12", 'cas_name' => "149-91-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "P - Coumaric Acid", 'molecular_wt' => "164.16", 'cas_name' => "501-98-4", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Ethanol Absolute Anhydrous", 'molecular_wt' => "46.08", 'cas_name' => "64-17-5", 'grade' => "AR", 'unit' => "L", 'chem_type' => "Chemical"),
    array('chemical_name' => "Fluorescein Sodium Salt", 'molecular_wt' => "332.31", 'cas_name' => "518-47-8", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "L - Ascorbic Acid", 'molecular_wt' => "176.12", 'cas_name' => "50-81-7", 'grade' => "AR", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Powder Manganese Citrate", 'molecular_wt' => "5", 'cas_name' => "1512", 'grade' => "Pharma", 'unit' => "g", 'chem_type' => "Chemical"),
    array('chemical_name' => "Valsartan", 'molecular_wt' => "5", 'cas_name' => "C-121", 'grade' => "Commercial", 'unit' => "g", 'chem_type' => "Chemical")
    );
}
