<?php
/** Default laboratory glassware seed list for Glassware Master. */
function medicap_standard_glasswares_seed() {
    return array(
    array('name' => 'Beaker', 'capacity' => '50', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Low form borosilicate beaker with spout', 'make' => 'Borosil'),
    array('name' => 'Beaker', 'capacity' => '100', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Low form borosilicate beaker with spout', 'make' => 'Borosil'),
    array('name' => 'Beaker', 'capacity' => '250', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Low form borosilicate beaker with spout', 'make' => 'Borosil'),
    array('name' => 'Beaker', 'capacity' => '500', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Low form borosilicate beaker with spout', 'make' => 'Borosil'),
    array('name' => 'Beaker', 'capacity' => '1000', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Low form borosilicate beaker with spout', 'make' => 'Borosil'),
    array('name' => 'Beaker', 'capacity' => '2000', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Low form borosilicate beaker with spout', 'make' => 'Borosil'),
    array('name' => 'Conical Flask', 'capacity' => '50', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Erlenmeyer flask, narrow mouth', 'make' => 'Borosil'),
    array('name' => 'Conical Flask', 'capacity' => '100', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Erlenmeyer flask, narrow mouth', 'make' => 'Borosil'),
    array('name' => 'Conical Flask', 'capacity' => '250', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Erlenmeyer flask, narrow mouth', 'make' => 'Borosil'),
    array('name' => 'Conical Flask', 'capacity' => '500', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Erlenmeyer flask, narrow mouth', 'make' => 'Borosil'),
    array('name' => 'Conical Flask', 'capacity' => '1000', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Erlenmeyer flask, narrow mouth', 'make' => 'Borosil'),
    array('name' => 'Volumetric Flask', 'capacity' => '5', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A volumetric flask with stopper', 'make' => 'Borosil'),
    array('name' => 'Volumetric Flask', 'capacity' => '10', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A volumetric flask with stopper', 'make' => 'Borosil'),
    array('name' => 'Volumetric Flask', 'capacity' => '25', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A volumetric flask with stopper', 'make' => 'Borosil'),
    array('name' => 'Volumetric Flask', 'capacity' => '50', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A volumetric flask with stopper', 'make' => 'Borosil'),
    array('name' => 'Volumetric Flask', 'capacity' => '100', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A volumetric flask with stopper', 'make' => 'Borosil'),
    array('name' => 'Volumetric Flask', 'capacity' => '200', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A volumetric flask with stopper', 'make' => 'Borosil'),
    array('name' => 'Volumetric Flask', 'capacity' => '250', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A volumetric flask with stopper', 'make' => 'Borosil'),
    array('name' => 'Volumetric Flask', 'capacity' => '500', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A volumetric flask with stopper', 'make' => 'Borosil'),
    array('name' => 'Volumetric Flask', 'capacity' => '1000', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A volumetric flask with stopper', 'make' => 'Borosil'),
    array('name' => 'Volumetric Flask', 'capacity' => '2000', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A volumetric flask with stopper', 'make' => 'Borosil'),
    array('name' => 'Measuring Cylinder', 'capacity' => '10', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Graduated measuring cylinder', 'make' => 'Borosil'),
    array('name' => 'Measuring Cylinder', 'capacity' => '25', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Graduated measuring cylinder', 'make' => 'Borosil'),
    array('name' => 'Measuring Cylinder', 'capacity' => '50', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Graduated measuring cylinder', 'make' => 'Borosil'),
    array('name' => 'Measuring Cylinder', 'capacity' => '100', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Graduated measuring cylinder', 'make' => 'Borosil'),
    array('name' => 'Measuring Cylinder', 'capacity' => '250', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Graduated measuring cylinder', 'make' => 'Borosil'),
    array('name' => 'Measuring Cylinder', 'capacity' => '500', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Graduated measuring cylinder', 'make' => 'Borosil'),
    array('name' => 'Measuring Cylinder', 'capacity' => '1000', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Graduated measuring cylinder', 'make' => 'Borosil'),
    array('name' => 'Volumetric Pipette', 'capacity' => '1', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A one-mark volumetric pipette', 'make' => 'Borosil'),
    array('name' => 'Volumetric Pipette', 'capacity' => '2', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A one-mark volumetric pipette', 'make' => 'Borosil'),
    array('name' => 'Volumetric Pipette', 'capacity' => '5', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A one-mark volumetric pipette', 'make' => 'Borosil'),
    array('name' => 'Volumetric Pipette', 'capacity' => '10', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A one-mark volumetric pipette', 'make' => 'Borosil'),
    array('name' => 'Volumetric Pipette', 'capacity' => '20', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A one-mark volumetric pipette', 'make' => 'Borosil'),
    array('name' => 'Volumetric Pipette', 'capacity' => '25', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A one-mark volumetric pipette', 'make' => 'Borosil'),
    array('name' => 'Volumetric Pipette', 'capacity' => '50', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A one-mark volumetric pipette', 'make' => 'Borosil'),
    array('name' => 'Graduated Pipette', 'capacity' => '1', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A graduated pipette', 'make' => 'Borosil'),
    array('name' => 'Graduated Pipette', 'capacity' => '2', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A graduated pipette', 'make' => 'Borosil'),
    array('name' => 'Graduated Pipette', 'capacity' => '5', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A graduated pipette', 'make' => 'Borosil'),
    array('name' => 'Graduated Pipette', 'capacity' => '10', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A graduated pipette', 'make' => 'Borosil'),
    array('name' => 'Graduated Pipette', 'capacity' => '25', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A graduated pipette', 'make' => 'Borosil'),
    array('name' => 'Burette', 'capacity' => '10', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A glass burette with PTFE stopcock', 'make' => 'Borosil'),
    array('name' => 'Burette', 'capacity' => '25', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A glass burette with PTFE stopcock', 'make' => 'Borosil'),
    array('name' => 'Burette', 'capacity' => '50', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Class A glass burette with PTFE stopcock', 'make' => 'Borosil'),
    array('name' => 'Nessler Cylinder', 'capacity' => '50', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Nessler comparison cylinder', 'make' => 'Borosil'),
    array('name' => 'Nessler Cylinder', 'capacity' => '100', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Nessler comparison cylinder', 'make' => 'Borosil'),
    array('name' => 'Test Tube', 'capacity' => '10', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Borosilicate test tube', 'make' => 'Borosil'),
    array('name' => 'Test Tube', 'capacity' => '15', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Borosilicate test tube', 'make' => 'Borosil'),
    array('name' => 'Test Tube', 'capacity' => '25', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Borosilicate test tube', 'make' => 'Borosil'),
    array('name' => 'Centrifuge Tube', 'capacity' => '15', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Glass centrifuge tube', 'make' => 'Borosil'),
    array('name' => 'Centrifuge Tube', 'capacity' => '50', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Glass centrifuge tube', 'make' => 'Borosil'),
    array('name' => 'Glass Funnel', 'capacity' => '50', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Short stem glass funnel', 'make' => 'Borosil'),
    array('name' => 'Glass Funnel', 'capacity' => '100', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Short stem glass funnel', 'make' => 'Borosil'),
    array('name' => 'Separating Funnel', 'capacity' => '125', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Pear shaped separating funnel with stopper', 'make' => 'Borosil'),
    array('name' => 'Separating Funnel', 'capacity' => '250', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Pear shaped separating funnel with stopper', 'make' => 'Borosil'),
    array('name' => 'Separating Funnel', 'capacity' => '500', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Pear shaped separating funnel with stopper', 'make' => 'Borosil'),
    array('name' => 'Separating Funnel', 'capacity' => '1000', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Pear shaped separating funnel with stopper', 'make' => 'Borosil'),
    array('name' => 'Reagent Bottle', 'capacity' => '125', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Amber reagent bottle with stopper', 'make' => 'Borosil'),
    array('name' => 'Reagent Bottle', 'capacity' => '250', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Amber reagent bottle with stopper', 'make' => 'Borosil'),
    array('name' => 'Reagent Bottle', 'capacity' => '500', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Amber reagent bottle with stopper', 'make' => 'Borosil'),
    array('name' => 'Reagent Bottle', 'capacity' => '1000', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Amber reagent bottle with stopper', 'make' => 'Borosil'),
    array('name' => 'Dropping Bottle', 'capacity' => '60', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Glass dropping bottle with pipette', 'make' => 'Borosil'),
    array('name' => 'Dropping Bottle', 'capacity' => '125', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Glass dropping bottle with pipette', 'make' => 'Borosil'),
    array('name' => 'Watch Glass', 'capacity' => '75', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Watch glass 75 mm', 'make' => 'Borosil'),
    array('name' => 'Watch Glass', 'capacity' => '100', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Watch glass 100 mm', 'make' => 'Borosil'),
    array('name' => 'Petri Dish', 'capacity' => '90', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Glass petri dish 90 mm', 'make' => 'Borosil'),
    array('name' => 'Petri Dish', 'capacity' => '100', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Glass petri dish 100 mm', 'make' => 'Borosil'),
    array('name' => 'Desiccator', 'capacity' => '150', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Vacuum desiccator with porcelain plate', 'make' => 'Borosil'),
    array('name' => 'Desiccator', 'capacity' => '200', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Vacuum desiccator with porcelain plate', 'make' => 'Borosil'),
    array('name' => 'Crucible with Lid', 'capacity' => '25', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Silica / porcelain crucible with lid', 'make' => 'Borosil'),
    array('name' => 'Crucible with Lid', 'capacity' => '50', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Silica / porcelain crucible with lid', 'make' => 'Borosil'),
    array('name' => 'Condenser Liebig', 'capacity' => '300', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Liebig condenser for distillation', 'make' => 'Borosil'),
    array('name' => 'Round Bottom Flask', 'capacity' => '250', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Single neck round bottom flask', 'make' => 'Borosil'),
    array('name' => 'Round Bottom Flask', 'capacity' => '500', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Single neck round bottom flask', 'make' => 'Borosil'),
    array('name' => 'Round Bottom Flask', 'capacity' => '1000', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Single neck round bottom flask', 'make' => 'Borosil'),
    array('name' => 'Iodine Flask', 'capacity' => '250', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Iodine determination flask with stopper', 'make' => 'Borosil'),
    array('name' => 'Iodine Flask', 'capacity' => '500', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Iodine determination flask with stopper', 'make' => 'Borosil'),
    array('name' => 'Karl Fischer Flask', 'capacity' => '100', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'KF titration vessel / flask', 'make' => 'Borosil'),
    array('name' => 'Glass Rod', 'capacity' => '1', 'unit' => 'ml', 'glassware_class' => 'type C', 'description' => 'Stirring glass rod', 'make' => 'Borosil'),
    array('name' => 'Glass Pipette Filler', 'capacity' => '1', 'unit' => 'ml', 'glassware_class' => 'type C', 'description' => 'Three-way pipette filler bulb', 'make' => 'Generic'),
    array('name' => 'Buchner Funnel', 'capacity' => '100', 'unit' => 'ml', 'glassware_class' => 'type B', 'description' => 'Porcelain Buchner funnel', 'make' => 'Generic'),
    array('name' => 'Filter Flask', 'capacity' => '500', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Vacuum filter flask with side arm', 'make' => 'Borosil'),
    array('name' => 'Filter Flask', 'capacity' => '1000', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Vacuum filter flask with side arm', 'make' => 'Borosil'),
    array('name' => 'Specific Gravity Bottle', 'capacity' => '25', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Pycnometer / specific gravity bottle', 'make' => 'Borosil'),
    array('name' => 'Specific Gravity Bottle', 'capacity' => '50', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Pycnometer / specific gravity bottle', 'make' => 'Borosil'),
    array('name' => 'Thermometer Pocket', 'capacity' => '1', 'unit' => 'ml', 'glassware_class' => 'type C', 'description' => 'Glass thermometer sleeve / pocket', 'make' => 'Borosil'),
    array('name' => 'HPLC Sample Vial', 'capacity' => '2', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Clear glass HPLC vial with cap', 'make' => 'Generic'),
    array('name' => 'HPLC Sample Vial Amber', 'capacity' => '2', 'unit' => 'ml', 'glassware_class' => 'type A', 'description' => 'Amber glass HPLC vial with cap', 'make' => 'Generic')
    );
}
