import { MasterExcelConfig } from './master-excel.types';

export const MASTER_EXCEL_CONFIGS: Record<string, MasterExcelConfig> = {
  MATERIAL_TYPE: {
    id: 'MATERIAL_TYPE',
    title: 'Material Type Master — Upload Format',
    sheetName: 'MaterialType',
    filePrefix: 'material_type_format',
    uploadUrl: 'master/materialtype.php?type=bulkInsertFromExcel',
    columns: [
      {
        key: 'material_type',
        header: 'Material Type',
        required: true,
        width: 22,
        sample: 'Raw Material',
        note: 'e.g. Raw Material / Packing Material',
      },
      {
        key: 'material_subtype',
        header: 'Material Subtype',
        required: true,
        width: 24,
        sample: 'API',
      },
      { key: 'Short_Code', header: 'Short Code', width: 14, sample: 'API' },
      {
        key: 'control_sample_type',
        header: 'Control/Reserve Sample',
        width: 22,
        sample: 'Yes',
      },
      {
        key: 'control_reserve_criteria',
        header: 'Control/Reserve Criteria',
        width: 24,
      },
      { key: 'retest_type', header: 'Retest', width: 14, sample: 'Yes' },
      { key: 'restest_months', header: 'Retest Months', width: 14, sample: '12' },
    ],
  },
  STORAGE_CONDITION: {
    id: 'STORAGE_CONDITION',
    title: 'Storage Condition Master — Upload Format',
    sheetName: 'StorageCondition',
    filePrefix: 'storage_condition_format',
    uploadUrl: 'master/master.php?type=bulkInsertFromExcel_storage',
    columns: [
      {
        key: 'storage_condition',
        header: 'Storage Condition',
        required: true,
        width: 28,
        sample: 'Store below 25°C',
      },
      {
        key: 'storage_display_name',
        header: 'Storage Display Name',
        width: 24,
        sample: 'Below 25C',
      },
      {
        key: 'temperature',
        header: 'Temperature',
        required: true,
        width: 16,
        sample: '25',
      },
      { key: 'humidity', header: 'Humidity(%)', width: 14, sample: '60' },
    ],
  },
  LAB: {
    id: 'LAB',
    title: 'Lab Master — Upload Format',
    sheetName: 'LabMaster',
    filePrefix: 'lab_master_format',
    uploadUrl: 'qc/lab.php?type=bulkInsertFromExcel',
    columns: [
      {
        key: 'lab_name',
        header: 'Lab Name',
        required: true,
        width: 28,
        sample: 'External QC Lab',
      },
      { key: 'contact_person', header: 'Contact Person', width: 20, sample: 'John Doe' },
      { key: 'contact_no', header: 'Contact No', width: 16, sample: '9876543210' },
      { key: 'email', header: 'Email', width: 26, sample: 'lab@example.com' },
      { key: 'address', header: 'Address', width: 36, sample: 'City, State' },
    ],
  },
  CHEMICAL: {
    id: 'CHEMICAL',
    title: 'Chemical Master — Upload Format',
    sheetName: 'ChemicalMaster',
    filePrefix: 'chemical_master_format',
    uploadUrl: 'qc/chemical.php?type=bulkInsertFromExcel',
    columns: [
      {
        key: 'chemical_name',
        header: 'Chemical Name',
        required: true,
        width: 28,
        sample: 'Sodium Hydroxide',
      },
      { key: 'grade', header: 'Grade', required: true, width: 14, sample: 'AR' },
      { key: 'molecular_wt', header: 'Molecular Wt (gm/mole)', width: 20, sample: '40' },
      { key: 'cas_name', header: 'CAS No', width: 18, sample: '1310-73-2' },
      { key: 'unit', header: 'Unit', width: 12, sample: 'gm' },
      { key: 'make', header: 'Make', width: 20, sample: 'Merck' },
    ],
  },
  GLASSWARE: {
    id: 'GLASSWARE',
    title: 'Glassware Master — Upload Format',
    sheetName: 'GlasswareMaster',
    filePrefix: 'glassware_master_format',
    uploadUrl: 'qc/glassware.php?type=bulkInsertFromExcel',
    columns: [
      { key: 'name', header: 'Name', required: true, width: 24, sample: 'Volumetric Flask' },
      { key: 'capacity', header: 'Capacity', required: true, width: 12, sample: '100' },
      { key: 'unit', header: 'Unit', required: true, width: 12, sample: 'ml' },
      { key: 'glassware_class', header: 'Class', required: true, width: 14, sample: 'A' },
      { key: 'make', header: 'Make', width: 18, sample: 'Borosil' },
      { key: 'hsn', header: 'HSN', width: 14 },
      { key: 'gst', header: 'GST', width: 12 },
      { key: 'description', header: 'Description', width: 28 },
    ],
  },
  VOLUMETRIC: {
    id: 'VOLUMETRIC',
    title: 'Volumetric Solution Master — Upload Format',
    sheetName: 'VolumetricMaster',
    filePrefix: 'volumetric_master_format',
    uploadUrl: 'qc/volumetric.php?type=bulkInsertFromExcel',
    columns: [
      {
        key: 'solution_type',
        header: 'Solution Type',
        required: true,
        width: 16,
        sample: 'Volumetric',
      },
      {
        key: 'solution_name',
        header: 'Solution Name',
        required: true,
        width: 28,
        sample: '0.1 N HCl',
      },
      { key: 'percentage', header: 'Percentage', width: 14 },
      { key: 'strength_unit', header: 'Unit', width: 12, sample: 'N' },
      { key: 'strength', header: 'Strength', width: 14, sample: '0.1' },
      { key: 'standard_type', header: 'Standard Type', width: 16 },
      { key: 'exp_date', header: 'Expiry Date', width: 14, sample: '2026-12-31', note: 'YYYY-MM-DD' },
    ],
  },
  EQUIPMENT: {
    id: 'EQUIPMENT',
    title: 'Equipment Master — Upload Format',
    sheetName: 'EquipmentMaster',
    filePrefix: 'equipment_master_format',
    uploadUrl: 'master/equipment.php?type=bulkInsertFromExcel',
    columns: [
      {
        key: 'equipment_category',
        header: 'Category',
        required: true,
        width: 16,
        sample: 'Production',
      },
      {
        key: 'equipment_type',
        header: 'Equipment Type',
        required: true,
        width: 22,
        sample: 'Blender',
      },
      {
        key: 'equipment_name',
        header: 'Equipment Name',
        required: true,
        width: 28,
        sample: 'Octagonal Blender',
      },
      {
        key: 'equipment_code',
        header: 'Equipment Id/Code',
        required: true,
        width: 18,
        sample: 'EQ-001',
      },
      { key: 'serial_no', header: 'Serial No', width: 16 },
      { key: 'make', header: 'Make', width: 16 },
      { key: 'model', header: 'Model', width: 16 },
      { key: 'department', header: 'Department', width: 18, sample: 'Production' },
      { key: 'location', header: 'Location', width: 18 },
    ],
  },
  MATERIAL_RM_PM: {
    id: 'MATERIAL_RM_PM',
    title: 'Raw / Packing Material Master — Upload Format',
    sheetName: 'MaterialMaster',
    filePrefix: 'rm_pm_material_format',
    uploadUrl: 'master/material.php?type=bulkInsertFromExcel',
    columns: [
      {
        key: 'material_type',
        header: 'Material Type',
        required: true,
        width: 18,
        sample: 'Raw Material',
        note: 'Must be Raw Material or Packing Material',
      },
      {
        key: 'material_subtype',
        header: 'Material Subtype',
        required: true,
        width: 22,
        sample: 'API',
      },
      {
        key: 'material_name',
        header: 'Material Name',
        required: true,
        width: 28,
        sample: 'Paracetamol',
      },
      {
        key: 'material_code',
        header: 'Material Code',
        width: 18,
        note: 'Optional; auto-generated if blank',
      },
      { key: 'grade', header: 'Grade', width: 14, sample: 'IP' },
      {
        key: 'material_nature',
        header: 'Material Nature',
        width: 16,
        sample: 'SOLID',
        note: 'SOLID / LIQUID / SEMI-SOLID',
      },
      { key: 'location', header: 'Location', width: 16 },
      { key: 'order_unit', header: 'Unit', width: 12, sample: 'Kg' },
      { key: 'hsn', header: 'HSN', width: 14 },
    ],
  },
  FINISHED_PRODUCT: {
    id: 'FINISHED_PRODUCT',
    title: 'Finished Product Master — Upload Format',
    sheetName: 'FinishedProduct',
    filePrefix: 'finished_product_format',
    uploadUrl: 'master/product.php?type=bulkInsertFromExcel',
    columns: [
      {
        key: 'product_code',
        header: 'Product Code',
        required: true,
        width: 16,
        sample: 'FP-001',
      },
      {
        key: 'product_name',
        header: 'Product Name',
        required: true,
        width: 28,
        sample: 'Sample Tablet 500mg',
      },
      { key: 'generic_name', header: 'Generic Name', width: 24, sample: 'Paracetamol' },
      {
        key: 'product_type',
        header: 'Product Type',
        width: 16,
        sample: 'Finished Product',
      },
      { key: 'category', header: 'Category', width: 16 },
      { key: 'dosage_form', header: 'Dosage Form', width: 16, sample: 'Tablet' },
      { key: 'dosage_type', header: 'Dosage Type', width: 14 },
      { key: 'grade', header: 'Grade', width: 14, sample: 'IP' },
      { key: 'shelf_life', header: 'Shelf Life', width: 12, sample: '24' },
      { key: 'storage_condition', header: 'Storage Condition', width: 22 },
    ],
  },
  TEST: {
    id: 'TEST',
    title: 'Test Master — Upload Format',
    sheetName: 'TestMaster',
    filePrefix: 'test_master_format',
    uploadUrl: 'master/test.php?type=bulkInsertFromExcel',
    columns: [
      {
        key: 'test_type',
        header: 'Test Type',
        required: true,
        width: 18,
        sample: 'Chemical',
      },
      {
        key: 'test',
        header: 'Test Name',
        required: true,
        width: 28,
        sample: 'Assay',
      },
      { key: 'test_method_no', header: 'Test Method No', width: 18 },
      {
        key: 'multiple_anaylist',
        header: 'Multiple Analyst (Yes/No)',
        width: 20,
        sample: 'NO',
      },
      {
        key: 'calculation',
        header: 'Calculation',
        width: 16,
        sample: 'Not Applicable',
      },
      {
        key: 'subtest',
        header: 'Subtest (optional)',
        width: 28,
        note: 'Creates one optional subtest row when filled',
      },
    ],
  },
  SPECIFICATION: {
    id: 'SPECIFICATION',
    title: 'Specification Master — Upload Format (header fields only)',
    sheetName: 'SpecificationHeader',
    filePrefix: 'specification_master_format',
    uploadUrl: 'qc/specification.php?type=bulkInsertFromExcel',
    columns: [
      {
        key: 'material_type',
        header: 'Material Type',
        required: true,
        width: 18,
        sample: 'Raw Material',
        note: 'Raw Material / Packing Material / Finished Product — header only; tests stay manual',
      },
      {
        key: 'material_code',
        header: 'Material/Product Code',
        required: true,
        width: 20,
        sample: 'MAT-00001',
      },
      {
        key: 'material_name',
        header: 'Material/Product Name',
        required: true,
        width: 28,
        sample: 'Paracetamol',
      },
      {
        key: 'specification_no',
        header: 'Specification No',
        width: 18,
        note: 'Optional; auto-generated if blank',
      },
      { key: 'version_no', header: 'Version No', width: 12, sample: '00' },
      { key: 'grade', header: 'Grade / Reference Type', width: 18, sample: 'IP' },
      {
        key: 'effective_date',
        header: 'Effective Date',
        width: 14,
        sample: '2026-08-01',
        note: 'YYYY-MM-DD',
      },
    ],
  },
};

export function getMasterExcelConfig(id: string): MasterExcelConfig {
  const cfg = MASTER_EXCEL_CONFIGS[id];
  if (!cfg) {
    throw new Error('Unknown master excel config: ' + id);
  }
  return cfg;
}
