CREATE TABLE IF NOT EXISTS `market_complaint` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `plant_id` text DEFAULT NULL,
  `user_no` text DEFAULT 'gmpdemo1',
  `complaint_no` varchar(50) DEFAULT NULL,
  `received_date` text DEFAULT NULL,
  `complaint_nature` text DEFAULT NULL,
  `complaint_sample` text DEFAULT NULL,
  `product_name` text DEFAULT NULL,
  `batch_no` text DEFAULT NULL,
  `mfg_date` text DEFAULT NULL,
  `exp_date` text DEFAULT NULL,
  `complaint_remark` text DEFAULT NULL,
  `control_remark` text DEFAULT NULL,
  `serevity` text DEFAULT NULL,
  `send_sample` text DEFAULT NULL,
  `status` varchar(50) DEFAULT 'pending',
  `entry_by` text DEFAULT NULL,
  `entry_date` text DEFAULT NULL,
  `check_by` text DEFAULT NULL,
  `check_date` text DEFAULT NULL,
  `investigation_start` text DEFAULT NULL,
  `investigation_complete` text DEFAULT NULL,
  `complaintent_type` text DEFAULT NULL,
  `received_from` text DEFAULT NULL,
  `contact_no` text DEFAULT NULL,
  `email` text DEFAULT NULL,
  `sendsample_to` text DEFAULT NULL,
  `severity` text DEFAULT NULL,
  `forward` text DEFAULT NULL,
  `physcian_email` text DEFAULT NULL,
  `departments` longtext DEFAULT NULL,
  `documents` longtext DEFAULT NULL,
  `observation` longtext DEFAULT NULL,
  `primary_observation` text DEFAULT NULL,
  `assessment` longtext DEFAULT NULL,
  `inspection_report` text DEFAULT NULL,
  `committeeList` longtext DEFAULT NULL,
  `complaint_report_no` text DEFAULT NULL,
  `complaint_report_date` text DEFAULT NULL,
  `compltNO` text DEFAULT NULL,
  `complaint_reference` text DEFAULT NULL,
  `complaint_details` longtext DEFAULT NULL,
  `preliminary_evaluation` longtext DEFAULT NULL,
  `root_cause` longtext DEFAULT NULL,
  `investigation_started` text DEFAULT NULL,
  `investigation_completed` text DEFAULT NULL,
  `investigation_method` longtext DEFAULT NULL,
  `observations_findings` longtext DEFAULT NULL,
  `conclusion` longtext DEFAULT NULL,
  `qms` text DEFAULT NULL,
  `tcd_action_taken` text DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_market_complaint_status` (`status`),
  KEY `idx_market_complaint_no` (`complaint_no`),
  KEY `idx_market_complaint_entry_date` (`entry_date`(32))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

COMMIT;
 