<?php




// ini_set('display_errors', 1);
// error_reporting(E_ALL);


require '../db.php';
require '../token.php';
require '../tcpdf/tcpdf.php';
header('Access-Control-Allow-Origin: *');
date_default_timezone_set("Asia/Kolkata");
$token = $_GET["token"];
$timestamp = time();
$entry_date = date("Y-m-d h:i:s", $timestamp);
$input = json_decode(file_get_contents('php://input'),true);

$sql = "SELECT * FROM token WHERE token='".$_GET["token"]."'";
$result = $conn->query($sql);
$_GET["emp_id"] = "";
$_GET["department"] = "";
if($result->num_rows > 0){
while($row = $result->fetch_assoc()){
	$string = decrypt('decrypt',$_GET["token"],$row["key1"],$row["key2"]);
	$string = explode("$",$string);
	$_GET["emp_id"] = $string[0];
	$_GET["department"] = $string[1];
	break;
}

$sql = "INSERT INTO log (process,token,action,actiontime,department,emp_id,method,REMOTE_ADDR) VALUES ('FRONTEND','".$token."','".$_GET["type"]."','".$entry_date."','".$_GET["department"]."','".$_GET["emp_id"]."','".$_SERVER['REQUEST_METHOD']."','".$_SERVER['REMOTE_ADDR']."')";
$conn->query($sql);

    if($_GET["type"]=="cyclonesave_sampling_batch"){ 
        
          $input = $_POST;
      
          $b = $input["batch_no"];
          $q = $input["qty_received"];
          $pId= $_GET["plant_id"];
        
        if(isset($_FILES["coa_file"])) {
            $file_tmp =$_FILES['coa_file']['tmp_name'];
            $file_ext=strtolower(end(explode('.',$_FILES['coa_file']['name'])));
            $coa_file = $pId.$b.$q."coa_file.".$file_ext;
        }
        

        $supplier_batch_no = isset($input["supplier_batch_no"]) ? $conn->real_escape_string($input["supplier_batch_no"]) : "";

        $sql = "INSERT INTO sampling_batches (plant_id,material_code,batch_no,supplier_batch_no,mfg_date ,pack_size ,total_containers ,qty_received ,exp_date,
        unit,challan_no,ch_no,mfg_by,coa_files,coa_received,materialFor,materialForName,clientGrpCode,clientSubGrpCode,tax_invoice) VALUES('".$_GET["plant_id"]."','".$_GET["material_code"]."',
        '".$input["batch_no"]."', '".$supplier_batch_no."', '".$input["mfg_date"]."','".$input["pack_size"]."','".$input["total_containers"]."', 
        '".$input["qty_received"]."','".$input["exp_date"]."' ,'".$input["unit"]."' ,'".$_GET["challan_no"]."','".$_GET["ch_no"]."',
        '".$_GET["mfg_by"]."','$coa_file','".$input["coa_received"]."','".$input["materialFor"]."','".$input["materialForName"]."','".$input["clientGrpCode"]."','".$input["clientSubGrpCode"]."','".$input["tax_invoice"]."' )";
        
    	if($conn->query($sql)){
    	    
    	       move_uploaded_file($file_tmp,"../../../upload/coa/".$coa_file);
 
                     
    		echo "{\"status\":\"success\"}";
    		
    	} else {
    		echo "{\"status\":\"".$conn->error."\"}";
    	}
        
    }
    else if($_GET["type"]=="cyclonesave_sampling_batchAlutin"){ 
        
          $input = $_POST;
           
          $b = $input["batch_no"];
          $q = $input["qty_received"];
          $pId= $_GET["plant_id"];
        
        if(isset($_FILES["coa_file"])) {
            $file_tmp =$_FILES['coa_file']['tmp_name'];
            $file_ext=strtolower(end(explode('.',$_FILES['coa_file']['name'])));
            $coa_file = $pId.$b.$q."coa_file.".$file_ext;
        }
        

        $supplier_batch_no = isset($input["supplier_batch_no"]) ? $conn->real_escape_string($input["supplier_batch_no"]) : "";

        $sql = "INSERT INTO sampling_batches (plant_id,material_code,batch_no,supplier_batch_no,mfg_date ,pack_size ,total_containers ,qty_received ,exp_date,
        unit,challan_no,ch_no,mfg_by,coa_files,coa_received,materialFor,materialForName,clientGrpCode,clientSubGrpCode,tax_invoice) VALUES('".$_GET["plant_id"]."','".$_GET["material_code"]."',
        '".$input["batch_no"]."', '".$supplier_batch_no."', '".$input["mfg_date"]."','".$input["pack_size"]."','".$input["total_containers"]."', 
        '".$input["qty_received"]."','".$input["exp_date"]."' ,'".$input["unit"]."' ,'".$_GET["challan_no"]."','".$_GET["ch_no"]."',
        '".$_GET["mfg_by"]."','$coa_file','".$input["coa_received"]."','".$input["materialFor"]."','".$input["materialForName"]."' , '".$input["clientGrpCode"]."','".$input["clientSubGrpCode"]."','".$input["tax_invoice"]."' )";
        
    	if($conn->query($sql)){
    	   $lastId = $conn->insert_id;
    	   $lastId = $conn->insert_id;

    	    move_uploaded_file($file_tmp,"../../../upload/coa/".$coa_file);

    	    
    	    if($input["batch_no"] == '#Autogenerated'){
    	       $batchNo = "BATC-".str_pad($lastId, 4, '0', STR_PAD_LEFT);
    	       $sql1 = "UPDATE sampling_batches SET batch_no = '$batchNo' WHERE id = '$lastId' ";
    	       $conn->query($sql1);
    	    }
 
                     
    		echo "{\"status\":\"success\"}";
    		
    	} else {
    		echo "{\"status\":\"".$conn->error."\"}";
    	}
        
    }


    else if($_GET["type"]=="saveCoaOfPendingBatches"){ 
            $input = $_POST;
          $b = $input["batch_no"];
          $q = $input["qty_received"];
          $pId= $_GET["plant_id"];
        
        if(isset($_FILES["coa_file"])) {
            $file_tmp =$_FILES['coa_file']['tmp_name'];
            $file_ext=strtolower(end(explode('.',$_FILES['coa_file']['name'])));
            $coa_file = $pId.$b.$q."coa_file.".$file_ext;
        }
        
        $sql = "UPDATE sampling_batches  SET coa_files = '$coa_file' where id = '".$input["id"]."'";
    	if($conn->query($sql)){
    	   move_uploaded_file($file_tmp,"../../../upload/coa/".$coa_file);
    		echo "{\"status\":\"success\"}";
    	} else {
    		echo "{\"status\":\"".$conn->error."\"}";
    	}
        
    }
else if($_GET["type"]=="get_save_sampling_batch"){
    
	$output = Array();
    $materialCodeEsc = $conn->real_escape_string((string)($_GET["material_code"] ?? ''));
    $challanNoEsc = $conn->real_escape_string((string)($_GET["challan_no"] ?? ''));
    $chNoEsc = $conn->real_escape_string((string)($_GET["ch_no"] ?? ''));
    $receivingNoEsc = $conn->real_escape_string((string)($_GET["receiving_no"] ?? ''));
    $plantIdEsc = $conn->real_escape_string((string)($_GET["plant_id"] ?? ''));

    $queries = array();
    if ($receivingNoEsc !== '') {
        $queries[] = "SELECT sb.* FROM sampling_batches sb
            INNER JOIN challan_materials cm ON sb.material_code = cm.material_code AND sb.challan_no = cm.challan_no
            WHERE cm.receiving_no = '".$receivingNoEsc."'
            ORDER BY sb.id ASC";
    }
    if ($materialCodeEsc !== '' && $challanNoEsc !== '') {
        $queries[] = "SELECT * FROM sampling_batches WHERE material_code = '".$materialCodeEsc."' AND challan_no = '".$challanNoEsc."' AND (plant_id = '".$plantIdEsc."' OR IFNULL(plant_id,'') = '') ORDER BY id ASC";
        $queries[] = "SELECT * FROM sampling_batches WHERE material_code = '".$materialCodeEsc."' AND challan_no = '".$challanNoEsc."' ORDER BY id ASC";
    }
    if ($materialCodeEsc !== '' && $chNoEsc !== '' && $chNoEsc !== $challanNoEsc) {
        $queries[] = "SELECT * FROM sampling_batches WHERE material_code = '".$materialCodeEsc."' AND (ch_no = '".$chNoEsc."' OR challan_no = '".$chNoEsc."') ORDER BY id ASC";
    }
    if ($challanNoEsc !== '' && $materialCodeEsc === '') {
        $queries[] = "SELECT * FROM sampling_batches WHERE challan_no = '".$challanNoEsc."' ORDER BY id ASC";
    }

    $seen = array();
    foreach ($queries as $sql) {
        $result = @$conn->query($sql);
        if ($result && $result->num_rows > 0) {
            while ($row = $result->fetch_assoc()) {
                $batchNo = trim((string)($row['batch_no'] ?? ''));
                if ($batchNo === '' || $batchNo === '#Autogenerated') {
                    continue;
                }
                $key = $batchNo.'|'.($row['challan_no'] ?? '').'|'.($row['id'] ?? '');
                if (!isset($seen[$key])) {
                    $seen[$key] = true;
                    $output[] = $row;
                }
            }
            if (count($output) > 0) {
                break;
            }
        }
    }
	
	echo json_encode($output);

} 
else if($_GET["type"]=="get_save_sampling_batchfor_deviation"){
    
	$output = Array();
 
     	  $sql = " select * from sampling_batches a left join vendor b on a.mfg_by=b.vendor_no where a.challan_no='".$_GET["challan_no"]."' 
     	  and a.coa_received='No' ";
    	
    	$result = $conn->query($sql);
    	if($result->num_rows > 0){
    		while($row = $result->fetch_assoc()){
    			$output[] = $row;
    		}
    	}
	
	echo json_encode($output);

} 
else if($_GET["type"]=="delete_save_sampling_batch"){
             $sql = "DELETE FROM sampling_batches where batch_no='".$_GET["batch_no"]."'" ;
         if ($conn->query($sql)) {
            echo "{\"status\":\"success\"}";
         }else {
            echo "{\"status\":\"".$conn->error."\"}";
        }
    }
}

 else {
    echo "{\"status\":\"invalid\"}";
}


$conn->close();
?>